# Generated by Django 3.0 on 2020-10-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pid', models.CharField(max_length=20, unique=True)),
                ('brand_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('offer_price', models.CharField(max_length=120)),
                ('mrp', models.CharField(max_length=120)),
                ('product_link', models.URLField()),
                ('image_file', models.ImageField(null=True, upload_to='products')),
                ('image_url', models.URLField()),
                ('keywords', models.ManyToManyField(blank=True, related_name='products', to='product.Keyword')),
            ],
        ),
    ]
